### PR TITLE
Catch IllegalStateException in onAttach for v3

### LINKED ISSUE #497: IllegalStateException in getSupportRequestManagerFragment
Since I've migrated more Glide calls to use fragment instead of application context I now receive a new crash report :

```
java.lang.RuntimeException: Unable to destroy activity xxx.ui.MediasListActivity}: java.lang.IllegalStateException: Activity has been destroyed
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4199)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4217)
       at android.app.ActivityThread.access$1500(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
Caused by: java.lang.IllegalStateException: Activity has been destroyed
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1399)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:637)
       at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:620)
       at com.bumptech.glide.manager.RequestManagerRetriever.getSupportRequestManagerFragment(RequestManagerRetriever.java:187)
       at com.bumptech.glide.manager.SupportRequestManagerFragment.onAttach(SupportRequestManagerFragment.java:116)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:907)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
       at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1965)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
       at android.support.v4.app.FragmentManagerImpl.moveToState$2563266(FragmentManager.java:1120)
       at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1966)
       at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:316)
       at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:158)
       at xxxx.ui.BaseActivity.onDestroy(BaseActivity.java:224)
       at android.app.Activity.performDestroy(Activity.java:6519)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4177)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4217)
       at android.app.ActivityThread.access$1500(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)

```

### PR DESCRIPTION
**Pull request by Teovald**
We should also fix this issue for Glide v3

Fixes #497.

### CODE REVIEW

File: library/src/main/java/com/bumptech/glide/manager/SupportRequestManagerFragment.java [hunk 1]
```diff
@@ -20,6 +21,9 @@
  * @see com.bumptech.glide.RequestManager
  */
 public class SupportRequestManagerFragment extends Fragment {
+
+    private static final String TAG = SupportRequestManagerFragment.class.getSimpleName();
```
Comment (TWiStErRob) [inline library/src/main/java/com/bumptech/glide/manager/SupportRequestManagerFragment.java]: This will throw for anyone starting to use Glide `SupportRequestManagerFragment` is 29 long and the max length is 23, that's why Sam used "RMFragment", please mimic the fix in v4.

**Comment by TWiStErRob** [comment]
Nice.

File: library/src/main/java/com/bumptech/glide/manager/SupportRequestManagerFragment.java (hunk 1 above)
Comment (Teovald) [inline library/src/main/java/com/bumptech/glide/manager/SupportRequestManagerFragment.java]: oh, so that's why he does not simply use getSimpleName. Good to know, I will update the PR.

**Comment by Teovald** [comment]
weird, I can successfully execute the gradle jar task locally.

**Comment by TWiStErRob** [comment]
It's not your code, it looks like @sjudd only removed the parallel switch for v4 builds on Travis, not v3, we didn't see failures on v3 so far... for some reason that switch was working for a long long time, and now it started to break.

**Comment by sjudd** [comment]
Something appears to have changed with travis. I've removed the parallel flag from 3.0 and it seems to build. Will wait for one more to finish, then I'll merge this. Thanks for the PR!
