### PR TITLE
Use Iterator.remove when trimming cache 

### LINKED ISSUE #2532: Crash when recycling Bitmaps too quickly
**Glide Version**: 4.2.0

**Integration libraries**: okhttp3-3.8.1

**Device/Android Version**: Emulator API Level 23, Kindle Fire Android 5.1

**Issue details / Repro steps / Use case background**: 
I have a RecyclerView full of LinearLayouts that contain largish ImageViews. They load asynchronously from the network. If I scroll fast enough after a while the app will crash.

**ModelLoader**:
```java
public class BGChartModelLoader extends BaseGlideUrlLoader<BGChart> {
    private final float mScale;

    protected BGChartModelLoader(ModelLoader<GlideUrl, InputStream> concreteLoader) {
        super(concreteLoader);

        final DisplayMetrics metrics = Resources.getSystem().getDisplayMetrics();
        mScale = metrics.density;
    }

    /**
     * The default factory for {@link }de.boersego.gmt.android.glide.BGChartModelLoader
     */
    public static class Factory implements ModelLoaderFactory<BGChart, InputStream> {

        @Override
        public ModelLoader<BGChart, InputStream> build(MultiModelLoaderFactory multiFactory) {
            return new BGChartModelLoader(multiFactory.build(GlideUrl.class, InputStream.class));
        }

        @Override
        public void teardown() {
        }
    }

    @Override
    protected String getUrl(final BGChart chart, final int width, final int height, final Options options) {
        final String locale = options.get(MyrGlideModule.OPTION_LOCALE);
        Float scaleOption = options.get(MyrGlideModule.OPTION_SCALE);
        final float scale = scaleOption != null ? scaleOption : mScale;

        return "http://charting.godmode-trader.de/t/app/config?id=" + chart.id + "&width=" + (width / mScale) + "&height=" + (height / mScale) + "&ratio=" + scale + "&_locale=" + locale;
    }

    @Override
    public boolean handles(BGChart o) {
        // We handle any Chart for now
        return true;
    }
}
```

**Glide load line in RelativeLayout subclass (list cell)**:
```java
            GlideApp.with(this).load((BGChart)mData)
                    .apply(RequestOptions.option(MyrGlideModule.OPTION_LOCALE, PanelDataSource.getInstance(getContext()).getLanguageCode()))
                    .error(R.drawable.ic_error_yellow_800_24dp)
                    .placeholder(new ActivityIndicatorDrawable(getContext()))
                    .into(mChartThumb);
```

**GlideModule**:
```java
@GlideModule
public class MyrGlideModule extends AppGlideModule {

    public static final Option<String> OPTION_LOCALE = Option.disk("locale", "en", new Option.CacheKeyUpdater<String>() {
        @Override
        public void update(byte[] keyBytes, String value, MessageDigest messageDigest) {
            messageDigest.update(keyBytes);
            messageDigest.update(value.getBytes());
        }
    });

    public static final Option<Float> OPTION_SCALE = Option.disk("scale", new Option.CacheKeyUpdater<Float>() {
        @Override
        public void update(byte[] keyBytes, Float value, MessageDigest messageDigest) {
            messageDigest.update(keyBytes);
            messageDigest.update(String.valueOf(value).getBytes());
        }
    });
    private static CircleBorderTransformation sCircleBorderTransform;

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        // Standard Glide options for the whole app. We want a smaller disk cache since we won't be loading big images
        // outside of WebView (which has it's own caching), and also set log level to high for non-debug builds
        builder.setLogLevel(BuildConfig.DEBUG ? Log.VERBOSE : Log.WARN);
        int diskCacheSizeBytes = 1024 * 1024 * 100; // 100 MB
        builder.setDiskCache(new InternalCacheDiskCacheFactory(context, diskCacheSizeBytes));
        // Initialize circle border transform paint from resources
    }

    @Override
    public void registerComponents(Context context, Glide glide, Registry registry) {
        registry.append(BGUser.class, InputStream.class, new AvatarModelLoader.Factory());
        registry.append(BGChart.class, InputStream.class, new BGChartModelLoader.Factory());
        registry.append(BGCountry.class, InputStream.class, new CountryModelLoader.Factory());
    }


}
```

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/chart_card"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:duplicateParentState="true"
    card_view:cardCornerRadius="3dp"
    card_view:cardElevation="2dp"
    card_view:cardUseCompatPadding="true">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@drawable/bg_selector_action_mode">

        <TextView
            android:id="@+id/chart_name"
            style="@style/font_bold"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentStart="true"
            android:layout_alignParentTop="true"
            android:layout_marginStart="11dp"
            android:layout_marginTop="11dp"
            android:layout_toStartOf="@+id/chart_date"
            android:ellipsize="end"
            android:maxLines="1"
            android:textColor="@color/veryDarkText"
            android:textIsSelectable="false"
            android:textSize="@dimen/TextStyleMedium"
            tools:text="Chart Analyse 2017" />

        <TextView
            android:id="@+id/chart_date"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentEnd="true"
            android:layout_alignParentTop="true"
            android:layout_marginEnd="11dp"
            android:layout_marginTop="11dp"
            android:maxLines="1"
            android:textColor="@color/bgo_grey"
            android:textIsSelectable="false"
            android:textSize="@dimen/TextStyleSmall"
            tools:text="19.10.2015" />

        <TextView
            android:id="@+id/chart_tags"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@+id/chart_name"
            android:layout_marginEnd="11dp"
            android:layout_marginStart="11dp"
            android:textColor="@color/bgo_grey"
            android:textIsSelectable="false"
            android:textSize="@dimen/TextStyleSmall"
            tools:text="Tags: Tag 1, Tag 2, Tag 3" />

        <ImageView
            android:id="@+id/chart_thumbnail"
            android:layout_width="match_parent"
            android:layout_height="195dp"
            android:layout_alignParentStart="true"
            android:layout_below="@+id/chart_tags"
            android:layout_marginTop="13dp"
            android:scaleType="centerCrop" />

    </RelativeLayout>

</android.support.v7.widget.CardView>
```

**Stack trace / LogCat**:
```ruby
                         E  java.lang.IllegalStateException: Cannot recycle a resource that has already been recycled
                         E      at com.bumptech.glide.load.engine.EngineResource.recycle(EngineResource.java:60)
                         E      at com.bumptech.glide.load.engine.ResourceRecycler.recycle(ResourceRecycler.java:28)
                         E      at com.bumptech.glide.load.engine.Engine.onResourceRemoved(Engine.java:311)
                         E      at com.bumptech.glide.load.engine.cache.LruResourceCache.onItemEvicted(LruResourceCache.java:31)
                         E      at com.bumptech.glide.load.engine.cache.LruResourceCache.onItemEvicted(LruResourceCache.java:11)
                         E      at com.bumptech.glide.util.LruCache.trimToSize(LruCache.java:175)
                         E      at com.bumptech.glide.util.LruCache.evict(LruCache.java:180)
                         E      at com.bumptech.glide.util.LruCache.put(LruCache.java:135)
                         E      at com.bumptech.glide.load.engine.cache.LruResourceCache.put(LruResourceCache.java:11)
                         E      at com.bumptech.glide.load.engine.Engine.onResourceReleased(Engine.java:319)
                         E      at com.bumptech.glide.load.engine.EngineResource.release(EngineResource.java:101)
                         E      at com.bumptech.glide.load.engine.Engine.release(Engine.java:277)
                         E      at com.bumptech.glide.request.SingleRequest.releaseResource(SingleRequest.java:324)
                         E      at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:303)
                         E      at com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(RequestTracker.java:62)
                         E      at com.bumptech.glide.RequestManager.untrack(RequestManager.java:443)
                         E      at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:430)
                         E      at com.bumptech.glide.RequestManager.clear(RequestManager.java:418)
                         E      at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:380)
                         E      at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:432)
                         E      at de.boersego.gmt.android.ui.cells.ChartCell.run(ChartCell.java:101)
                         E      at de.boersego.gmt.android.ui.cells.ChartCell.setData(ChartCell.java:86)
                         E      at de.boersego.gmt.android.base.BGRecycleListAdapter.onBindViewHolder(BGRecycleListAdapter.java:451)
                         E      at de.boersego.gmt.android.base.BGRecycleListAdapter.onBindViewHolder(BGRecycleListAdapter.java:44)
                         E      at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6482)
                         E      at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6515)
                         E      at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5458)
                         E      at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5724)
                         E      at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
                         E      at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
                         E      at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
                         E      at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
                         E      at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
                         E      at android.os.Handler.handleCallback(Handler.java:739)
                         E      at android.os.Handler.dispatchMessage(Handler.java:95)
                         E      at android.os.Looper.loop(Looper.java:135)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5484)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at java.lang.reflect.Method.invoke(Method.java:372)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                         I  To Report FATAL to activityManagerService
        ActivityManager  I  handleApplicationCrash
                         W    Force finishing activity 1 de.boersego.gmt.android/.MainActivityOverride
```

### PR DESCRIPTION
**Pull request by unverbraucht**
## Description

Instead of explicitly removing a key from the LruCache (which fails if the key class violates the equals() contract) call remove() on the iterator instead.

## Motivation and Context

Using this even cache keys violating equals() can be used here. Fixes #2532.

### CODE REVIEW

**Comment by unverbraucht** [comment]
I signed it!

**Comment by unverbraucht** [comment]
I'm unable to change the email on the CLA, it is always set to my gmail addresseven after changing my Google settings to use my new one. Maybe somebody else can re-apply the patch?

File: library/src/main/java/com/bumptech/glide/util/LruCache.java [hunk 1]
```diff
@@ -166,12 +168,13 @@ public void clearMemory() {
...
+    final Iterator<Map.Entry<T, Y>> cacheIterator = cache.entrySet().iterator();
     while (currentSize > size) {
-      last = cache.entrySet().iterator().next();
+      last = cacheIterator.next();
       final Y toRemove = last.getValue();
       currentSize -= getSize(toRemove);
       final T key = last.getKey();
-      cache.remove(key);
+      cacheIterator.remove();
       onItemEvicted(key, toRemove);
```
Comment (TWiStErRob) [inline library/src/main/java/com/bumptech/glide/util/LruCache.java]: is there a chance of `ConcurrentModificationException` because of this line?

Comment (unverbraucht) [reply library/src/main/java/com/bumptech/glide/util/LruCache.java]: No, using the Iterator to remove is safe when using the Iterator itself to loop over the collection. I added another commit to ensure that we don't overrun the collection, although I don't see how it could happen unless the size to trim to is <0. Can't hurt though I guess.

**Comment by sjudd** [comment]
LGTM, just waiting on 4.3.1 to go out before merging.

File: library/src/main/java/com/bumptech/glide/util/LruCache.java (hunk 1 above)
Comment (TWiStErRob) [reply library/src/main/java/com/bumptech/glide/util/LruCache.java]: @sjudd before you merge, please consider this test:
```java
  @Test
  public void testPreventEviction() {
    final MemoryCache cache = new LruResourceCache(100);
    final Resource<?> first = getResource(30);
    final Key firstKey = new MockKey();
    cache.put(firstKey, first);
    Resource<?> second = getResource(30);
    Key secondKey = new MockKey();
    cache.put(secondKey, second);
    Resource<?> third = getResource(30);
    Key thirdKey = new MockKey();
    cache.put(thirdKey, third);
    cache.setResourceRemovedListener(new ResourceRemovedListener() {
      @Override
      public void onResourceRemoved(Resource<?> removed) {
        if (removed == first) {
          cache.put(firstKey, first);
        }
      }
    });

    // trims from 100 to 50, having 30+30+30 items, it should trim to 1 item
    cache.trimMemory(ComponentCallbacks2.TRIM_MEMORY_UI_HIDDEN);

    // and that 1 item must be first, because it's forced to return to cache in the listener
    @SuppressWarnings("unchecked")
    LruCache<Key, Resource<?>> lruCache = (LruCache<Key, Resource<?>>) cache;
    assertTrue(lruCache.contains(firstKey));
    assertFalse(lruCache.contains(secondKey));
    assertFalse(lruCache.contains(thirdKey));
  }
```

Comment (sjudd) [reply library/src/main/java/com/bumptech/glide/util/LruCache.java]: @unverbraucht thoughts? I don't think we typically have concurrent modifications like this, but it's probably possible (and may be why the code was written the way it was initially).

Comment (unverbraucht) [reply library/src/main/java/com/bumptech/glide/util/LruCache.java]: @sjudd @TWiStErRob good point. It might make sense then to get a fresh instance of the Iterator after every loop run. I've committed proposed changes for that.

File: library/src/main/java/com/bumptech/glide/util/LruCache.java [hunk 2]
```diff
@@ -166,12 +168,14 @@ public void clearMemory() {
    */
   protected synchronized void trimToSize(int size) {
     Map.Entry<T, Y> last;
+    Iterator<Map.Entry<T, Y>> cacheIterator;
```
Comment (TWiStErRob) [inline library/src/main/java/com/bumptech/glide/util/LruCache.java]: just a preference (declare close to usage, and in scope): these two vars are only used within the loop, so they could be defined inside:
```
final Iterator<Map.Entry<T, Y>> cacheIterator  = cache.entrySet().iterator();
final Map.Entry<T, Y> last = cacheIterator.next();
```

Comment (sjudd) [reply library/src/main/java/com/bumptech/glide/util/LruCache.java]: I agree in principle, but this matches the existing style, so let's just leave it as is for now.

**Comment by sjudd** [comment]
Thanks!
